apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: os-pkg-plan-agent
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      # will trigger upgrade for any node that does not contain the 'node-role.kubernetes.io/control-plane' label
      - {key: node-role.kubernetes.io/control-plane, operator: NotIn, values: ["true"]}
  serviceAccountName: system-upgrade-controller
  secrets:
    - name: os-pkg-update
      path: /host/run/system-upgrade/secrets/os-pkg-update
  cordon: true
  version: "3.0.0"
  upgrade:
    image: registry.opensuse.org/opensuse/tumbleweed:latest
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/os-pkg-update/update.sh"]
