apiVersion: v1
kind: Secret
metadata:
  name: os-pkg-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    secrets=$(dirname $0)

    echo "-------------"
    whoami
    echo "-------------"

    echo "-------------"
    cd /sbin
    ls -alh
    echo "-------------"

    sleep infinity

    transactional-update -n
    # Ensure that no accidental reboots happen.
    # Ensure that the upgrade Pod has time to uncordon the node
    # before the restart.
    [ -f /run/reboot-needed ] && shutdown -r +1