apiVersion: v1
kind: Secret
metadata:
  name: eib-chart-upgrade-script
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -eo pipefail

    chart_data_path=/run/system-upgrade/secrets/eib-chart-upgrade-user-data/chart_upgrade_data.txt
    manifest_dir=

    determineManifestPath(){
        echo "Determining path to RKE2/K3s manifests directory"

        if [ -d /etc/rancher/rke2/ ]; then
            manifest_dir=/var/lib/rancher/rke2/server/manifests
        elif [ -d /etc/rancher/k3s/ ]; then
            manifest_dir=/var/lib/rancher/k3s/server/manifests
        else 
            echo "RKE2/K3s manifest directory not found."
            exit 1
        fi
    }

    backupManifest(){
        backup_manifest=${1}

        if [ -z "${MANIFEST_BACKUP_DIR}" ]; then
            date_suffix=`date -d "today" +"%Y%m%d%H%M"`
            backup_location=/tmp/eib-helm-chart-upgrade-${date_suffix}
            mkdir -p ${backup_location}
        else
            backup_location=${MANIFEST_BACKUP_DIR}
        fi

        echo "Backing up ${backup_manifest} under ${backup_location}"
        cp ${backup_manifest} ${backup_location}
    }

    updateChartArchive(){
        while IFS= read -r chart_data; do
            [ -z "$chart_data" ] && continue
            echo "---"

            name=`cut -d '|' -f 1 <<< "$chart_data"`
            version=`cut -d '|' -f 2 <<< "$chart_data"`
            archive=`cut -d '|' -f 3- <<< "$chart_data"`
            chart_manifest_path=${manifest_dir}/${name}.yaml

            backupManifest ${chart_manifest_path}
            
            echo "Modifying the 'chartContent' property of the ${chart_manifest_path} manifest file"
            sed -i "s|chartContent:.*|chartContent: $archive|" ${chart_manifest_path}

            echo "Modifying the 'version' property of the ${chart_manifest_path} manifest file"
            sed -i "s|version:.*|version: $version|" ${chart_manifest_path}

            echo "${chart_manifest_path} chart manifest has been successfully modified."

        done < "${chart_data_path}"
    }

    main(){
        determineManifestPath
        updateChartArchive
    }

    main
